version: 2
jobs:
  cross_compile:
    docker:
      - image: circleci/golang:1.11
    steps:
      - setup_remote_docker
      - run: docker pull karalabe/xgo-latest
      - run: mkdir /tmp/solstice
      - run: docker run --name xgo karalabe/xgo-latest github.com/reserve-protocol/solstice
      - run: docker cp xgo:/build /tmp/solstice
      - store_artifacts:
          path: /tmp/solstice
  run_unit_tests:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/reserve-protocol/solstice
    steps:
      - checkout
      - run: ls
      - run: dep ensure
      - run: go test ./tests
  build_command:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/reserve-protocol/solstice
    steps:
      - checkout
      - run: dep ensure
      # Ideally we want to test each command, but it will take a lot more work
      # to pull a repo with solidity contracts and tests, and boot up a
      # blockchain here. This at least makes sure it builds.
      - run: go build -o solstice
      - run: ./solstice
      - run: ./solstice help
      - run: ./solstice --help
      - run: ./solstice -h

workflows:
  version: 2
  test_all:
    jobs:
      - cross_compile
      - run_unit_tests
      - build_command
